version: 2.1
jobs:
  build:
    docker:
      - image: node:18.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npx playwright install --with-deps
      - run:
          name: Run Playwright Tests
          command: npx playwright test
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report-first
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-test:
    jobs:
      - build