version: 2.1

jobs:
  build:
    machine: true   # Necesario para usar docker build/run
    working_directory: ~/repo

    steps:
      - checkout

      # Construir imagen Docker personalizada
      - run:
          name: Build Docker image
          command: docker build -t playwright-tests .

      # Ejecutar tests dentro del contenedor
      - run:
          name: Run Playwright Tests in Docker
          command: |
            docker run --rm \
              -v $(pwd)/playwright-report:/app/playwright-report \
              -v $(pwd)/src:/app/src \
              playwright-tests

      # Guardar artifacts (reporte HTML)
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report

      # Guardar resultados de test (CircleCI los interpreta)
      - store_test_results:
          path: ./playwright-report

workflows:
  version: 2
  build-test:
    jobs:
      - build
