version: 2.1

jobs:
  build-and-test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      # Construir imagen Docker de Playwright
      - run:
          name: Build Playwright Docker image
          command: docker build -t playwright-tests .

      # Preparar directorio de reportes con timestamp y guardar TIMESTAMP
      - run:
          name: Prepare report directories
          command: |
            mkdir -p ~/repo/reports-history
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
            echo "$TIMESTAMP" > ~/repo/reports-history/.last_run
            REPORT_DIR=~/repo/reports-history/$TIMESTAMP
            mkdir -p "$REPORT_DIR"
            echo "$TIMESTAMP" > "$REPORT_DIR/timestamp.txt"
            echo "$CIRCLE_BRANCH" > "$REPORT_DIR/branch.txt"
            echo "$CIRCLE_SHA1" > "$REPORT_DIR/commit.txt"

      # Ejecutar tests dentro del contenedor Docker
      - run:
          name: Run Playwright tests in Docker
          command: |
            TIMESTAMP=$(cat ~/repo/reports-history/.last_run)
            docker run --rm \
              -v ~/repo/reports-history/$TIMESTAMP:/app/reports \
              playwright-tests \
              npx playwright test --reporter=html

      # Actualizar symlink "latest"
      - run:
          name: Update latest report symlink
          command: |
            TIMESTAMP=$(cat ~/repo/reports-history/.last_run)
            rm -rf ~/repo/reports-history/latest || true
            ln -s ~/repo/reports-history/$TIMESTAMP ~/repo/reports-history/latest

      # Guardar artifacts
      - store_artifacts:
          path: ~/repo/reports-history
          destination: playwright-reports

      # Generar dashboard HTML
      - run:
          name: Generate HTML Dashboard
          command: |
            TIMESTAMP=$(cat ~/repo/reports-history/.last_run)
            bash ~/repo/scripts/generate_dashboard.sh ~/repo/reports-history/$TIMESTAMP

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
