version: 2.1

executors:
  playwright-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: playwright-executor
    steps:
      - checkout

      # Construir la imagen de Docker con tu Dockerfile
      - run:
          name: Build Playwright Docker image
          command: docker build -t playwright-tests .

      # Crear carpetas de reportes con timestamp
      - run:
          name: Prepare report directories
          command: |
            mkdir -p ~/repo/reports-history
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
            export REPORT_DIR=~/repo/reports-history/$TIMESTAMP
            mkdir -p $REPORT_DIR
            echo $TIMESTAMP > $REPORT_DIR/timestamp.txt
            echo $CIRCLE_BRANCH > $REPORT_DIR/branch.txt
            echo $CIRCLE_SHA1 > $REPORT_DIR/commit.txt

      # Ejecutar tests dentro del contenedor Docker
      - run:
          name: Run Playwright tests in Docker
          command: |
            docker run --rm \
              -v ~/repo/reports-history/$TIMESTAMP:/app/reports \
              playwright-tests

      # Actualizar enlace "latest"
      - run:
          name: Update latest report symlink
          command: |
            rm -rf ~/repo/reports-history/latest || true
            ln -s ~/repo/reports-history/$TIMESTAMP ~/repo/reports-history/latest

      # Guardar artifacts para descargar desde CircleCI
      - store_artifacts:
          path: ~/repo/reports-history
          destination: playwright-reports

      # Generar dashboard HTML
      - run:
          name: Generate HTML Dashboard
          command: bash scripts/generate_dashboard.sh

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
