version: 2.1

jobs:
  build-and-test:
    machine: true  # Necesario para usar Docker
    working_directory: ~/repo
    steps:
      - checkout

      # Construir imagen Docker de Playwright
      - run:
          name: Build Playwright Docker image
          command: docker build -t playwright-tests .

      # Preparar directorio de reportes con timestamp
      - run:
          name: Prepare report directories
          command: |
            mkdir -p ~/repo/reports-history
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
            echo "export TIMESTAMP=$TIMESTAMP" >> $BASH_ENV
            source $BASH_ENV
            REPORT_DIR=~/repo/reports-history/$TIMESTAMP
            mkdir -p "$REPORT_DIR"

            # Guardar metadata temporal en otro lugar
            mkdir -p ~/repo/reports-metadata/$TIMESTAMP
            echo "$TIMESTAMP" > ~/repo/reports-metadata/$TIMESTAMP/timestamp.txt
            echo "$CIRCLE_BRANCH" > ~/repo/reports-metadata/$TIMESTAMP/branch.txt
            echo "$CIRCLE_SHA1" > ~/repo/reports-metadata/$TIMESTAMP/commit.txt

      # Ejecutar tests dentro del contenedor Docker y guardar reportes HTML
      - run:
          name: Run Playwright tests in Docker
          command: |
            source $BASH_ENV
            docker run --rm \
              -v ~/repo/reports-history/$TIMESTAMP:/app/reports \
              playwright-tests \
              npx playwright test --reporter=html --output=/app/reports

      # Restaurar metadata porque Playwright sobreescribe el directorio
      - run:
          name: Restore metadata
          command: |
            source $BASH_ENV
            cp ~/repo/reports-metadata/$TIMESTAMP/*.txt ~/repo/reports-history/$TIMESTAMP/

      # Actualizar symlink "latest"
      - run:
          name: Update latest report symlink
          command: |
            source $BASH_ENV
            rm -rf ~/repo/reports-history/latest || true
            ln -s ~/repo/reports-history/$TIMESTAMP ~/repo/reports-history/latest

      # Guardar artifacts para descargar desde CircleCI
      - store_artifacts:
          path: ~/repo/reports-history
          destination: playwright-reports

      # Generar dashboard HTML
      - run:
          name: Generate HTML Dashboard
          command: |
            source $BASH_ENV
            bash ~/repo/scripts/generate_dashboard.sh ~/repo/reports-history/$TIMESTAMP

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
