version: 2.1

jobs:
  build:
    machine: true   # Necesario para usar docker build/run
    working_directory: ~/repo

    steps:
      - checkout

      # Construir imagen Docker personalizada
      - run:
          name: Build Docker image
          command: docker build -t playwright-tests .

      # Ejecutar tests dentro del contenedor
      - run:
          name: Run Playwright Tests in Docker
          command: |
            docker run --rm \
              -v $(pwd)/reports:/app/reports \
              -v $(pwd)/src:/app/src \
              playwright-tests

      # Guardar artifacts (HTML + Allure)
      - store_artifacts:
          path: ./reports/html
          destination: playwright-html-report

      - store_artifacts:
          path: ./reports/allure-results
          destination: playwright-allure-results

      # Guardar resultados de test (JUnit para CircleCI)
      - store_test_results:
          path: ./reports/junit

workflows:
  version: 2
  build-test:
    jobs:
      - build
