name: Playwright Tests (Docker + Pages)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 👈 ejecutar manualmente también

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1. Build Docker image desde tu Dockerfile
      - name: Build Playwright Docker image
        run: docker build -t playwright-tests .

      # 2. Run tests dentro del contenedor
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            playwright-tests

      # 3. Subir reportes como artifact (descargable desde GitHub Actions)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: reports/html
          retention-days: 30

      # 4. Guardar el reporte en carpeta con timestamp para historial
      - name: Prepare timestamped report folder
        if: always()
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
          mkdir -p "reports-history/$TIMESTAMP"
          cp -r reports/html/* "reports-history/$TIMESTAMP/"
          echo "REPORT_PATH=reports-history/$TIMESTAMP" >> $GITHUB_ENV

      # 5. Publicar en GitHub Pages con historial
      - name: Upload report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports-history
          publish_branch: gh-pages
