name: Playwright Tests (Docker)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1. Build Docker image desde tu Dockerfile
      - name: Build Playwright Docker image
        run: docker build -t playwright-tests .

      # 2. Run tests dentro del contenedor
      #    Guardamos reportes en un volumen para extraerlos
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            playwright-tests

      # 3. Subir reportes de Playwright como artifact
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: reports/html
          retention-days: 30
